pipeline:
  name: hello-world-pipeline
  tasks:
    - name: step1
      type: python
      notebook_path: scripts/hello.py

    - name: step2
      type: python
      notebook_path: scripts/world.py
      depends_on: step1
